### PR TITLE
refactor gulp structure, add tinify util task

### PR DESCRIPTION
**Pull request by akrawchyk**

### CODE REVIEW

**Comment by akrawchyk** [comment]
@josephabrahams @recursivefunk @heyitsolivia @thomasdegry let me know what you think of these changes

**Comment by recursivefunk** [comment]
Will it significantly increase build times? We're pretty image heavy in our designs. Then again, the alternative is huge images slipping into prod so maybe it doesn't matter much.

**Comment by akrawchyk** [comment]
@recursivefunk so the tinify task doesn't run during build/dev because of increased build times (and 500 images/month for the free tier of https://tinypng.com/developers). For now, you need to run it manually and commit the changes.

**Comment by recursivefunk** [comment]
Ah OK cool I think that's probably better for now.

**Comment by recursivefunk** [comment]
👍

**Comment by josephabrahams** [comment]
But you have to have an account to use it?

On Sat, Jun 18, 2016, 11:02 AM Johnny Ray Austin <notifications@github.com>
wrote:

> 👍
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/istrategylabs/mo-static/pull/51#issuecomment-226946979>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACwvBUYrzGNbVABsSYXCAqxp0hIpYR9_ks5qNAihgaJpZM4I33-q>
> .
>
-- 

*Joseph Abrahams* | VP of Engineering
ISL <https://isl.co/> | 256.302.0500
Twitter <http://twitter.com/josephabrahams> | LinkedIn
<https://www.linkedin.com/in/josephabrahams>

**Comment by akrawchyk** [comment]
@josephabrahams yep, the accounts are free and you just need to set the TINIFY_API_KEY env var.

Or, we couldrig up imagemin. The annoying part is they only bundle the lossless plugins by default https://github.com/sindresorhus/gulp-imagemin#api so we'd need to do some manual configuring.

**Comment by heyitsolivia** [comment]
👍 new gulp structure looks good to me

**Pull request merged**
