### PR TITLE
Minification working

### PR DESCRIPTION
**Pull request by thomasdegry**
Not sure about what options we want in our HTML compression, or JS and CSS ones either.
Css and JS ones are empty now, html just has `collapseWhiteSpaces` set to `true` for now.
If feedback about these or other changes I'll update the PR!

### CODE REVIEW

**Comment by josephabrahams** [comment]
How did I add the `in progress` label? I didn't do anything.

**Comment by thomasdegry** [comment]
@josephabrahams I swear to god, it does it automatically, it freaks me out.

**Comment by josephabrahams** [comment]
I bet it's waffle. Weird.

On Wed, Nov 11, 2015, 8:36 PM Thomas Degry <notifications@github.com> wrote:

> @josephabrahams <https://github.com/josephabrahams> I swear to god, it
> does it automatically, it freaks me out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/istrategylabs/mo-static/pull/8#issuecomment-155969317>
> .
>
-- 

*Joseph Abrahams* | VP of Engineering
ISL <https://isl.co/> | 256.302.0500
Twitter <http://twitter.com/josephabrahams> | LinkedIn
<https://www.linkedin.com/in/josephabrahams>

**Comment by akrawchyk** [comment]
@thomasdegry can you add the settings listed here to html min? https://github.com/istrategylabs/mo-static/issues/5#issue-116340872

**Comment by akrawchyk** [comment]
Why did you remove the `public_path` from cookiecutter.json?

**Comment by akrawchyk** [comment]
Nvm, if you remove that then, can you replace all of the `{{ cookiecutter.public_path }}` references?

**Comment by thomasdegry** [comment]
@akrawchyk done and done! Updated PR

**Pull request merged**
